### ISSUE TITLE
Runs Allowed (Pitching, PitchingPost, Teams)

### ISSUE THREAD

**Issue by mswilson4040** [chadwickbureau/baseballdatabank#100]
The **Runs Allowed** column has inconsistent naming conventions. In **Pitching** and **PitchingPost**, the column name is **R**. However, in **Teams** its labeled as **RA**

I'm assuming this was due to the fact that the **Teams** data has a **Runs** column which is already taking up the **R** column name.

It would be nice if column names were consistent.

**Comment by tturocy** [comment]
This is a legacy schema.  It was created by someone else in the 1990s; we only maintain it.  There are countless and untold downstream uses which would break if we changed the schema.  There are any number of ways in which this is not the schema we would have designed; however,  it is what it is and it's trivial with modern tools to re-map column names however a downstream application would like to do.
