### ISSUE TITLE
Special Character in people.csv

### ISSUE THREAD

**Issue by Maradonna90** [chadwickbureau/baseballdatabank#106]
There is a spanish special character in Cionel Perez name. I haven't found it anywhere else in `people.csv`.
He is called `Cionel Pérez` in the file, all other people are written `Perez`. Might consider changing it for consistency

**Comment by tturocy** [comment]
This is not an error.  At present players in the Cuban National Series are rendered with their names as appearing in that league's averages.  This will be expanded to other players of Latin descent whose names are rendered inclusive of accents and tildes, where that is routinely done in English-speaking media.
