### ISSUE TITLE
Do you need help with the Awards tables?

### ISSUE THREAD

**Issue by cwoodruff** [chadwickbureau/baseballdatabank#110]
I am offering help if the following tables need help being updated:
- AwardsManagers.csv
- AwardsPlayers.csv
- AwardsShareManagers.csv
- AwardsSharePlayers.csv

These tables need the following year's data created: 2017-2020

**Comment by markknopper** [comment]
AwardsManagers seems to have data only through 2016. Would it be possible to get it updated in baseballdatabank?
