### ISSUE TITLE
Negro League Statistics

### ISSUE THREAD

**Issue by pburney** [chadwickbureau/baseballdatabank#112]
Hi all. I appreciate the great work you are doing here to preserve baseball history and make it accessible to all.

The MLB has finally recognized the Negro Leagues as Major Leagues:
https://www.mlb.com/press-release/press-release-mlb-officially-designates-the-negro-leagues-as-major-league

And some other sites are starting to support stats and other information from the Negro Leagues:
https://www.retrosheet.org/NegroLeagues/index.html
https://www.baseball-reference.com/register/negro-league-stats.shtml

Are there any plans for the baseballdatabank to include such information in the future?

**Comment by brianckeegan** [comment]
There are details on Retrosheet's efforts [here](https://www.retrosheet.org/NegroLeagues/NegroLeagues.html). I would also be willing to volunteer my students' time and our access to archival materials to these efforts.

**Comment by tturocy** [comment]
From the README:

*This is a legacy resource. Data in this format has been circulated by various people for many years, and there are many applications and users who have tools which take data in this format. It is maintained by Chadwick Baseball Bureau to support compatibility with those tools and programs. As such, the schema is not open to amendments, either in terms of the scope of coverage or in terms of the data categories available.*

Negro Leagues data is outside the scope of this offering.  We do have plenty of Negro Leagues data and have the ability to license it, but we will not be offering it as part of this free resource.

Of course, as this is an extensible resource, anyone is free to create a derivative product which incorporates the Negro Leagues, or indeed any other additional data they might want to.
