### ISSUE TITLE
TOS Permissions for the baseballdatabank/core/People.csv file

### ISSUE THREAD

**Issue by vicjanicki** [chadwickbureau/baseballdatabank#115]
Can I use the baseballdatabank/core/People.csv file content in GitHub for my personal websites, Android apps and IOS apps.
These are sites and apps external to GitHub that I will host on other servers.
I would be creating free and paid versions of the websites and apps.

**Comment by tturocy** [comment]
From the README:

``This work is licensed under a Creative Commons Attribution-ShareAlike
3.0 Unported License.  For details see:
http://creativecommons.org/licenses/by-sa/3.0/
``
