### ISSUE TITLE
Importing errors

### ISSUE THREAD

**Issue by charlymoon** [chadwickbureau/baseballdatabank#116]
On batting.csv I had several errors on the table import wizard from MySQL, thanks in advance

**Comment by tturocy** [comment]
I'm sorry to hear that.  You should fix your script.

**Comment by charlymoon** [comment]
No problem, it seems like MySQL workbench does not like the "empty" values on the files, if someone ask a possible solution is to edit the files (via Libreoffice calc or excel) and fill the empty values with 0 or any convenient value. Thanks anyway and hope this note can help someone else

**Comment by tturocy** [comment]
Any tool that cannot correctly import null values is broken.  You should use a different one.

And in case someone else does see this: Filling empty values is an ABSOLUTELY HORRIBLE IDEA.  DO NOT DO IT!  Understand the problem with your import tool and fix it.  RANDOMLY CHANGING DATA IS BAD!

**Comment by charlymoon** [comment]
Sorry, you are right... i expressed my self badly... NULL is a valid value, the tool is expecting the word NULL since NULL is a different value than empty, so, if you want to use this specific tool and have the null values you must specify that the value is NULL. You are right,  CHANGING DATA IS BAD... Please forgive my previous comment.
