### ISSUE TITLE
Possible to add MLB Advanced Media Team Ids?

### ISSUE THREAD

**Issue by jzuhusky** [chadwickbureau/baseballdatabank#118]
I've noticed while using the MLB Stats API that each team has an integer ID. Would it be possible to add this to the teams.csv file as a new column similar to how the Chadwick Persons register contains MLBAM ids (key_mlbam).

**Comment by tturocy** [comment]
This is a legacy product which is provided solely for backwards compatibility with applications which use it, which we maintain as a courtesy to the community.  As such it's not open for schema changes or extensions.
