### ISSUE TITLE
the bbrefID for John J. O'Neil (Buck O'Neil) is oneilbu01

### ISSUE THREAD

**Issue by heike** [chadwickbureau/baseballdatabank#133]
the bbrefID for John J. O'Neil (Buck O'Neil) is oneilbu01

please see:
https://en.wikipedia.org/wiki/Buck_O%27Neil
https://www.baseball-reference.com/players/o/oneilbu01.shtml

**Comment by tturocy** [comment]
Yes, and this is what the files have.
