### ISSUE TITLE
Fielding.csv - G less than GS

### ISSUE THREAD

**Issue by djznidarsic** [chadwickbureau/baseballdatabank#137]
Dear Chadwick,

About 300 entries in the Fielding.csv spreadsheet I downloaded in January contain a G column which is less than the GS column. Is there is a scoring oddity which credits a player with a game started at a position, but not with a game played at that same position?

Attached to this Github issue is a spreadsheet of the entries in Fielding.csv where the G column is less than the GS column.

David

[Chadwick - Fielding - G less than GS.xlsx](https://github.com/chadwickbureau/baseballdatabank/files/11133300/Chadwick.-.Fielding.-.G.less.than.GS.xlsx)

**Comment by tturocy** [comment]
This is a legacy resource which we have agreed to continue hosting as a courtesy to the community.  Most of the data do not originate with us, and we do not provide any support for its use.

We can provide some general advice:

(1) The historical record is not internally consistent, and there are very many imbalances.  This is especially true of fielding data.
(2) The rules for awarding a game fielded at a position have changed throughout history, and further were not always consistently applied in the official statistics.
(3) Games started is not an official statistic and would have been compiled from unofficial sources, so (1) and (2) imply that there may well be "impossible" combinations.
