### ISSUE TITLE
Add Citing?

### ISSUE THREAD

**Issue by nmcassa** [chadwickbureau/baseballdatabank#140]
It might be helpful to add citing for academic works that may want to use this. 

https://academia.stackexchange.com/questions/14010/how-do-you-cite-a-github-repository

https://citation-file-format.github.io/

**Comment by tturocy** [comment]
People should **under no circumstances** use this for academic research.  Not because the license doesn't permit it, but because this is a legacy resource, and errors in the legacy portion of the data will not be corrected.

We have updated the README to make this more clear.
