### ISSUE TITLE
Fielding data missing for outfielders

### ISSUE THREAD

**Issue by Dreslough** [chadwickbureau/baseballdatabank#19]
Most outfielders are missing fielding data by position in the newest version of Fielding.csv. All stats are clumped into 'OF' instead of being divided out by position.

Corrected file attached.
[Fielding.zip](https://github.com/chadwickbureau/baseballdatabank/files/280224/Fielding.zip)

**Comment by tturocy** [comment]
Thanks. Not breaking out by LF/CF/RF is the intended behaviour, as those are not official statistics.
