### ISSUE TITLE
Appearances.CSV - 2014 Multi-Team Players

### ISSUE THREAD

**Issue by orrski** [chadwickbureau/baseballdatabank#31]
In Appearances.CSV, it looks like all players who played for multiple teams in 2014 have only one entry. This was literally fixed for John Axford in pull request #29 , but it turns out to be a much larger issue than one player.

**Comment by tturocy** [comment]
I have re-applied the tool now used to build Appearances (the 2014 data did not come from me), which is generated based on the retrosplits repository.  This has the effect of correcting the 2014 data from commit 7540134.
