### ISSUE TITLE
Bad dates for Player ID "johnsbi01"?

### ISSUE THREAD

**Issue by CQH** [chadwickbureau/baseballdatabank#36]
- `Fielding.csv` has records for `johnsbi01` for 1844, 1887, 1890, 1891, & 1892 (a 48 year span)
- `Batting.csv` also has records for `johnsbi01` for 1844, 1887, 1890, 1891, & 1892.
- `Master.csv` has `johnsbi01` being born in 1961.
- There are no data points for a `johnsbi01` born after 1961.

Further, I think these _could_ be 2 people:
- One playing in the mid 1800s
- One playing in the late 1800s

This would explain the 48 year span in records...unless he did play into his 60s or 70s.

**Comment by orrski** [comment]
PlayerId johnsbi01's entry in Master.csv corresponds with BBrefId johnsbi01, and his [BBRef page](http://www.baseball-reference.com/players/j/johnsbi01.shtml) lists him as being born on September 28, 1861, while Master.CSV table says September 29, 1961. Master.csv and his BBRef page agree on his death date, however. I think the Master.CSV entry for his birth year is a typo.

I also can't find any entries for 1844 in Fielding.csv or Batting.csv. But I could find johnsbi01 entries for 1884.

**Comment by CQH** [comment]
> I also can't find any entries for 1844 in Fielding.csv or Batting.csv. But I could find johnsbi01 entries for 1884.

Yeah, apparently that's a typo on my part.  Should be 1884.

So, with that revelation, I agree that johnsbi01 is the same born in 1861 that you found on BBRef.
