### ISSUE TITLE
2016 awards data

### ISSUE THREAD

**Issue by tturocy** [chadwickbureau/baseballdatabank#40]
Updates for the following files are solicited:

* AwardsManagers.csv
* AwardsPlayers.csv
* AwardsShareManagers.csv
* AwardsSharePlayers.csv
* HallofFame.csv

**Comment by cBrou** [comment]
Updated 2016 popular awards list including TSN and Comeback etc...

[awards.csv.zip](https://github.com/chadwickbureau/baseballdatabank/files/676015/awards.csv.zip)

**Comment by seanlahman** [comment]
Submitted updates for all five of those files

**Comment by tturocy** [comment]
I've processed the updates from @seanlahman for four of five - the HoF file needs a reformat first before it can be merged.  So almost there.

**Comment by seanlahman** [comment]
Cleaned up formatting and resubmiited the HoF file.
