### ISSUE TITLE
Hal Dues missing for 1977

### ISSUE THREAD

**Issue by 110phil** [chadwickbureau/baseballdatabank#49]
There is no row in the pitching table for Hal Dues 1977 season.  1978 and 1980 are there.  (Quick check: the sum of the Expos wins for the 1977 season is one short, and Hal Dues had one win that year.)

Don't have time to research and upload a correction this weekend, so leaving it here for now.

**Comment by jasonmm** [comment]
The Expos' record for 1977 appears to [now be correct](https://github.com/chadwickbureau/baseballdatabank/blob/master/core/Teams.csv#L1725), 75-87.
