### ISSUE TITLE
Salaries.csv - A.J. Pierzynski 2016 playerID

### ISSUE THREAD

**Issue by orrski** [chadwickbureau/baseballdatabank#58]
In Salaries.csv, A.J. Pierzynski's 2016 salary entry has playerID "pierza.01" instead of "pierzaj01". This is in row 25623.

**Comment by tturocy** [comment]
@seanlahman Did you mistakenly use B-R IDs instead of BBDB?  They aren't the same!

**Comment by seanlahman** [comment]
ugh. Yes.  Error in my script.

**Comment by tturocy** [comment]
@seanlahman I think there are others that are incorrect too in the salaries - are you planning to re-build or do I need to do it?  I'd like to issue a corrected version if we can.

**Comment by seanlahman** [comment]
I will rebuild.  My script kicked out bbrefIDs instead of bbdbIDs on the
tables I updated.  Fixes will be posted shortly.

---
Sean Lahman
http://seanlahman.com
@SeanLahman

**Comment by tturocy** [comment]
Superseded by 8a3cf0e.

**Comment by LeeZee1** [comment]
I too thought that the correct format was BBR (key_bbref).  There are 346 rows in Salaries table for which the mlb_id IS NULL when I tried to add a mlb_id column matched on key_bbref.  This has been a problem as I cannot add salaries for all players based on mlb_id in my atbats-pitches merged mlbam table.  Not sure how to resolve it.
