### ISSUE TITLE
PitchingPost.csv - 1973 GDP Figure Decimal Instead of Int

### ISSUE THREAD

**Issue by orrski** [chadwickbureau/baseballdatabank#59]
In PitchingPost.csv, the GDP entries for the 1973 entries are all decimal data types instead of integers (i.e. they end with ".0"). This looks to only be happening for 1973, which looks to span from rows 1082 - 1124.

**Comment by mjaltamirano** [comment]
I encountered this as well. I changed the entries to be integers in my dataset. The values include: 0.0, 1.0, 2.0. I did not see any others.

**Comment by tturocy** [comment]
Fixed in d9a406e.
