### ISSUE TITLE
HallOfFame.csv J.D. Drew 2017 PlayerId

### ISSUE THREAD

**Issue by orrski** [chadwickbureau/baseballdatabank#60]
J.D. Drew's 2017 entry in HallOfFame.csv has his playerID as "drewj.01" instead of "drewjd01". This is in row 4150.

**Comment by tturocy** [comment]
@seanlahman Did you mistakenly use B-R IDs instead of BBDB?  They aren't the same!

**Comment by tturocy** [comment]
Superseded by 8a3cf0e.
