### ISSUE TITLE
Missing non-infinite ERA values in PitchingPost.csv

### ISSUE THREAD

**Issue by DavidRFoss** [chadwickbureau/baseballdatabank#64]
Hello,

I am seeing 28 missing non-infinite ERA values between blakesh01 in 1929 and moosebo01 in 1972.  I can recalculate them from ER and IPOuts, but just letting you know.

Thanks.
-David

**Comment by tturocy** [comment]
Performance tables are built via scripts, and as such manual edits of them are not useful (as any manual edits would just be overwritten in the next build).

All postseason data from 1903 onward has been re-built from latest Retrosheet for the 2018 release, so ERAs should be handed consistently throughout this table.
