### ISSUE TITLE
AwardsPlayers table missing TSN All-Star for 2008-2015

### ISSUE THREAD

**Issue by bdilday** [chadwickbureau/baseballdatabank#65]
AwardsPlayers table seems to be missing all stars for 2008-2015

**Comment by tturocy** [comment]
Pull requests are always welcomed!

**Comment by bdilday** [comment]
The AllstarFull table actually had what I was looking for.

**Comment by tturocy** [comment]
The AllstarFull tables doesn't have TSN all-stars; that is something different.
