### ISSUE TITLE
Batting PlayerID Does Not Exist in list of People

### ISSUE THREAD

**Issue by gadashek** [chadwickbureau/baseballdatabank#67]
Batting [PlayerID] = thompar01

exists in Batting. does not exist in People

**Comment by tturocy** [comment]
This player has been determined to be Fred Tenney.

The person register is updated daily, but statistical tables are only rebuilt in December.

**Comment by gadashek** [comment]
That does not make sense. Please recheck your data.
That player should be Arthur J. "Art" Thompson. Played in 1884

**Comment by tturocy** [comment]
Our data are correct.  Art Thompson did not play Major League Baseball - the game in question, as I already said, was played by Fred Tenney.
