### ISSUE TITLE
Update Awards tables

### ISSUE THREAD

**Issue by tturocy** [chadwickbureau/baseballdatabank#70]
The following tables need updating:

* AwardsPlayers (now updated as of commit 14d41442).
* AwardsSharePlayers
* AwardsManagers
* AwardsShareManagers

**Comment by cBrou** [comment]
Added 2017 player awards including TSN all-stars.  This continues from 2016.

[AwardsPlayers.csv.zip](https://github.com/chadwickbureau/baseballdatabank/files/1704958/AwardsPlayers.csv.zip)

**Comment by tturocy** [comment]
Many thanks - can you please to use the pull request mechanism to integrate this?

**Comment by tturocy** [comment]
AwardsPlayers is now updated as of 14d41442.
