### ISSUE TITLE
There are 4 schoolID's in CollegePlaying table that do not have schoolID in Schools table

### ISSUE THREAD

**Issue by cwoodruff** [chadwickbureau/baseballdatabank#78]
I am creating a MSSQL database based on the CVS files and I have found that there are 4 schoolID's in CollegePlaying that do not have a corresponding schoolID in Schools data. The schoolID's are:

ctpostu
txutper
txrange
caallia

**Comment by tturocy** [comment]
Those tables are at present not maintained/supported.  They've been left in as legacy.
