### ISSUE TITLE
There is references in AllstarFull table that do not have matching row in Teams table

### ISSUE THREAD

**Issue by cwoodruff** [chadwickbureau/baseballdatabank#79]
I am creating an MSSQL database based on the CVS files and I have found that there is a reference in AllstarFull table that does not have a matching row in Teams table. The teamID, lgID and yearID are:

teamID = 'ANA'
lgID = 'AL'
yearID = 2017

**Comment by tturocy** [comment]
Corrected in 0cdc91c.
