### ISSUE TITLE
Cammeyer was determined to be a phantom

### ISSUE THREAD

**Issue by Pleetteet** [chadwickbureau/baseballdatabank#8]
The following entry needs to be removed from the Managers table (Managers.csv file), if we are not going to add the master record for Bill Cammeyer:

cammebi99,1876,NY3,NL,1,57,21,35,6,N

-Mark

> There is a missing Master record corresponding to the Manager record for Bill Cammeyer. The most recent year that this guy was in the Master file was 2013, and it looked like this:
> 
> 2037,,cammebi99m,,1821,3,20,USA,NY,New York,1898,9,4,USA,NY,Brooklyn,Bill,Cammeyer,,William Henry,,,,,,,,,cammebi99,cammebi99,cammb801,cammebi99,cammebi99
>

**Comment by orrski** [comment]
I think that Manager.csv entry could be replaced with the following:

cravebi01,1876,NY3,NL,1,57,21,35,6,N

According to Retrosheet, Bill Craver was New York's manager in 1876 (http://www.retrosheet.org/boxesetc/C/Pcravb101.htm), and according to Baseball Reference, Bill Cammeyer was only a field manager (http://www.baseball-reference.com/managers/cammebi99.shtml).

**Comment by tturocy** [comment]
Yes; I just hadn't done it yet, was going to get to it in the offseason.  Corrected in d43381c
