### ISSUE TITLE
Teams > teamID: CHN

### ISSUE THREAD

**Issue by mswilson4040** [chadwickbureau/baseballdatabank#83]
In the teams table, there's 142 records for the `teamID` 'CHN'. If you look through the records, it's a mix of Chicago White Sox and Chicago Cubs. Looks like the Chicago White Sox started in 1904 so shouldn't that count be closer to 114?

**Comment by tturocy** [comment]
I can't reproduce this.  There are 142 records for CHN, which is correct, as the club has been in the NL since its founding and the league has played 142 seasons.  The AL has played 117 seasons and there are 117 records for CHA.

**Comment by mswilson4040** [comment]
I'm still confused on why Chicago Cubs would be tied to the same ID as the White Sox. When you ran the same query `teamdID = "CHN"` you didn't receive any Chicago Cubs data back?

![image](https://user-images.githubusercontent.com/19480392/42067672-4096543c-7afc-11e8-86ef-2d0c32c26611.png)

**Comment by mswilson4040** [comment]
Disregard. I'm an idiot and was just staring at things way too long. CHN is Chicago Cubs and CHA is the White Sox. After googling, It looks like the Chicago White Stockings was the name of the team prior to becoming the Cubs which started in 1870. The data make sense now due to lack of knowledge the White Stocking are not White Sox.
