### ISSUE TITLE
Assistance?

### ISSUE THREAD

**Issue by mswilson4040** [chadwickbureau/baseballdatabank#84]
I have been playing around with this dataset for a couple years now and I love it. I primarily use MongoDB to store all of the csv's in this repo and recently created a utility to easily pull down this repo and transform it so that it can upload to MongoDB without any effort.

Do you guys have any need for assistance/tooling/ui work (data visualizations or the like)? I would love to help!

https://www.npmjs.com/package/chadwick-to-mongo

**Comment by tturocy** [comment]
Tooling and UI is something well beyond the scope of this project, which we define strictly to be about producing portable data files, and we leave applications to downstream people. But many thanks for your enquiry.

**Comment by mswilson4040** [comment]
Fiar enough. I was thinking more along the lines of building some visualizations around areas in the data that need attention. Seeing what else is out there to verify information and spot check data. Really just tools around making sure the data is rich and accurate as possible.

**Comment by tturocy** [comment]
This is a restricted/delayed version of the data feeds we provide to our professional clients, including several major websites you might have used from time to time. What you propose doesn't sound like a terribly useful exercise.
