### ISSUE TITLE
Column Names

### ISSUE THREAD

**Issue by mswilson4040** [chadwickbureau/baseballdatabank#88]
I'm sure this falls under a 'breaking change' if someone has any automation around building a database from your repo, but I thought I'd at least inquire about it.

Would it be possible to format column names that follows SQL standards (filed names can't start with a number)?

Example -> Batting.csv 2B, 3B

I think these are the only column I've had an issue with so far. I know these two columns are found in multiple csv files. I can of course just translate them in my automation process, but would like keep it matching the what's in this repo as much as possible.

**Comment by tturocy** [comment]
This is the schema we have inherited, which has been used for 20 years.  It's not the schema I would design if starting from scratch today.

Nevertheless, your request is based on a false (although commonly held) premise. We produce clean data files with well-defined semantics. Those semantics are tool-agnostic.  It is the job of the user to write an appropriate filter to convert the text file to their preferred data structure.  I myself don't really give a fig about SQL; I do everything in some combination of R, pandas, and STATA.  Obviously other people might want to use other tools, and that's fine, but it is beyond the scope of what we do (with our free offerings) to do this work for people.
