### ISSUE TITLE
Managers table has an entry with missing PlayerID

### ISSUE THREAD

**Issue by markknopper** [chadwickbureau/baseballdatabank#90]
The following line appears in the Managers.csv table:

`,2018,SLN,NL,2,69,38,31,3,N
`
ie. it is missing the PlayerID field. This should be Mike Schildt, who does not seem to have a master Players record either.

-Mark

**Comment by tturocy** [comment]
2018 managers records are corrected in 9995e4b.  Shildt was already in the people table in v2019.1.

**Comment by markknopper** [comment]
Ah, my mistake. Thanks!
