### ISSUE TITLE
Some 1800s integer fields weirdly expressed as floats

### ISSUE THREAD

**Issue by richlowe** [chadwickbureau/baseballdatabank#92]
The HBP field in Pitching.csv, and the CS and SB fields in Teams.csv contain some unexpectedly float values (all <something>.0), mostly if not all in the 1880s.  

This chokes some unfortunately strict database imports.

**Comment by tturocy** [comment]
Corrected in 107da9f.  Took the opportunity to clean up the build pipeline to use the new nullable int type in pandas, which is ultimately the source of the problem.
