### ISSUE TITLE
2018 data missing for entire teams across multiple CSVs including PostBatting.csv and PostPitching.csv

### ISSUE THREAD

**Issue by jakeliebow1997** [chadwickbureau/baseballdatabank#93]
Data for teams and more importantly players from certain teams are entirely missing from two very useful datasets PostBatting.csv and PostPitching.csv.

**Comment by d0325mgray** [comment]
Do you know if the SQL Server version have the same problems? Give me a couple of examples and I'll check it out

**Comment by jakeliebow1997** [comment]
I don't have a SQL server set up on my computer right now so I didn't try, as for an example look up Diego Castillo or any player for the Arizona Diamondbacks on the PostPitching.csv

**Comment by jakeliebow1997** [comment]
There isn't one pitcher listed in the PostPitching csv for the Arizona Diamond backs.

**Comment by jakeliebow1997** [comment]
I just pulled out all unique teamIDs for the 2018 season out of the PostPitching csv and this is what I got.
ATL
BOS
CHN
CLE
COL
HOU
LAN
MIL
NYA
OAK

**Comment by d0325mgray** [comment]
The postpitching table has players for ARI. I only looked for Diego Castillo and got plenty of hits for him.

I didn't spend a lot of time on this but will do some more searching tomorrow. I am in Cambodia and it is getting to be dinner time.

**Comment by d0325mgray** [comment]
Are you only concerned with the 2018 season? Arizona did not have any team in the playoffs in 2018 so why would you be expecting to see records for them in the pitchingPost table or, maybe I don't understand exactly what your looking for.

```
use LahmansBaseballDB
select
	a.nameLast
	, a.nameGiven
	, a.playerID
	, b.yearID
	, b.teamID
from
	People a
	, PitchingPost b
where
	a.playerID = b.playerID
and
	b.teamID = 'ARI'
and
	b.yearID = 2018

```

**Comment by tturocy** [comment]
Could you please be specific as to what the claimed problem is?

Also, this product and the Lahman database are not the same thing - we would appreciate it if the two are not confused.

**Comment by d0325mgray** [comment]
What is the difference between "this product" and the Lahman database?

**Comment by jakeliebow1997** [comment]
For some reason I was only able to read in data up to the year 2000 in the batting and pitching csvs. I was able to access data in 2018 for the Post season datasets and incorrectly assumed that the 'Post' meant post 2000s. Re-downloading the datasets fixed the issue. My apologies, feel free to close the ticket.
