### ISSUE TITLE
Script(s) to load MySQL from the CSV files

### ISSUE THREAD

**Issue by d0325mgray** [chadwickbureau/baseballdatabank#94]
I've poked around and couldn't find any scripts to load the CSV files. Do they exist?

**Comment by tturocy** [comment]
What do you mean by "load the CSV files"?  CSV files are CSV files; that is the product.

**Comment by rippinrobr** [comment]
I have a repo https://github.com/rippinrobr/baseball-stats-db , that contains backups of the data from MySQL, Postgres, and SQLite.  Check the releases.

**Comment by d0325mgray** [comment]
rippinrobr  Many thanks. This is exactly what I was looking for.
