### ISSUE TITLE
TeamsHalf/ManagersHalf CSVs

### ISSUE THREAD

**Issue by mswilson4040** [chadwickbureau/baseballdatabank#95]
The TeamsHalf csv only has 52 records and the ManagersHalf has 93. Have these csvs lost importance over time or is it un-maintained? Only curious because I'm expecting a lot more data to be in there. Trying to get a better understanding if the *half.csv's are unimportant if I'm already using the non-half table.

Example:

Managers vs ManagersHalf
Teams vs TeamsHalf

I'm assuming as long as I've got Managers/Teams, the half files are redundant?

**Comment by tturocy** [comment]
These are for years in which a split-season was played.
